import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/components/QueryProvider";
import SocketContext from "@/context/socket-context";
import ChatContext from "@/context/ChatContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} dark antialiased bg-background`}
      >
        <ChatContext>
          <SocketContext>
            <QueryProvider>
              {children}
            </QueryProvider>
          </SocketContext>
        </ChatContext>
        <div id="portal"></div>
      </body>
    </html>
  );
}
